# Generated by Django 5.0.6 on 2024-05-22 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 5, 22, 19, 52, 51, 659418)),
        ),
    ]
